version: '1'

services:
  app:
    image: 'eventshuffle-backend:latest'
    build:
      context: eventshuffle-backend
    container_name: eventshuffle-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - eventshuffle-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: eventshuffle-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - eventshuffle-network

networks:
  eventshuffle-network:
    driver: bridge