version: '3.8'

services:
  app:
    image: happosade/eventshuffle
    build:
      context: eventshuffle-backend
    container_name: eventshuffle-backend
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - eventshuffle-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:postgres/5432
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
    env_file:
      - .env

  db:
    image: 'postgres:13.1-alpine'
    container_name: eventshuffle-postgres
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - '5432:5432'
    networks:
      - eventshuffle-network
    env_file:
      - .env

networks:
  eventshuffle-network:
    driver: bridge

