/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventDate implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDate proposedDate;
    private Long eventId;

    public EventDate() {
    }

    public EventDate(EventDate value) {
        this.id = value.id;
        this.proposedDate = value.proposedDate;
        this.eventId = value.eventId;
    }

    public EventDate(
            Long id,
            LocalDate proposedDate,
            Long eventId
    ) {
        this.id = id;
        this.proposedDate = proposedDate;
        this.eventId = eventId;
    }

    /**
     * Getter for <code>EVENT_DATE.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>EVENT_DATE.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>EVENT_DATE.PROPOSED_DATE</code>.
     */
    public LocalDate getProposedDate() {
        return this.proposedDate;
    }

    /**
     * Setter for <code>EVENT_DATE.PROPOSED_DATE</code>.
     */
    public void setProposedDate(LocalDate proposedDate) {
        this.proposedDate = proposedDate;
    }

    /**
     * Getter for <code>EVENT_DATE.EVENT_ID</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>EVENT_DATE.EVENT_ID</code>.
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EventDate other = (EventDate) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (proposedDate == null) {
            if (other.proposedDate != null)
                return false;
        } else if (!proposedDate.equals(other.proposedDate))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        } else if (!eventId.equals(other.eventId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.proposedDate == null) ? 0 : this.proposedDate.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventDate (");

        sb.append(id);
        sb.append(", ").append(proposedDate);
        sb.append(", ").append(eventId);

        sb.append(")");
        return sb.toString();
    }
}
