/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Events implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer eventId;
    private String name;

    public Events() {
    }

    public Events(Events value) {
        this.eventId = value.eventId;
        this.name = value.name;
    }

    public Events(
            Integer eventId,
            String name
    ) {
        this.eventId = eventId;
        this.name = name;
    }

    /**
     * Getter for <code>EVENTS.EVENT_ID</code>.
     */
    public Integer getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>EVENTS.EVENT_ID</code>.
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * Getter for <code>EVENTS.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>EVENTS.NAME</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Events other = (Events) obj;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        } else if (!eventId.equals(other.eventId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Events (");

        sb.append(eventId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
