/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventDateVote implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String votingPerson;
    private Long eventDateId;
    private Long version;

    public EventDateVote() {
    }

    public EventDateVote(EventDateVote value) {
        this.id = value.id;
        this.votingPerson = value.votingPerson;
        this.eventDateId = value.eventDateId;
        this.version = value.version;
    }

    public EventDateVote(
            Long id,
            String votingPerson,
            Long eventDateId,
            Long version
    ) {
        this.id = id;
        this.votingPerson = votingPerson;
        this.eventDateId = eventDateId;
        this.version = version;
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.VOTING_PERSON</code>.
     */
    public String getVotingPerson() {
        return this.votingPerson;
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.VOTING_PERSON</code>.
     */
    public void setVotingPerson(String votingPerson) {
        this.votingPerson = votingPerson;
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.EVENT_DATE_ID</code>.
     */
    public Long getEventDateId() {
        return this.eventDateId;
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.EVENT_DATE_ID</code>.
     */
    public void setEventDateId(Long eventDateId) {
        this.eventDateId = eventDateId;
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.VERSION</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.VERSION</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EventDateVote other = (EventDateVote) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (votingPerson == null) {
            if (other.votingPerson != null)
                return false;
        } else if (!votingPerson.equals(other.votingPerson))
            return false;
        if (eventDateId == null) {
            if (other.eventDateId != null)
                return false;
        } else if (!eventDateId.equals(other.eventDateId))
            return false;
        if (version == null) {
            if (other.version != null)
                return false;
        } else if (!version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.votingPerson == null) ? 0 : this.votingPerson.hashCode());
        result = prime * result + ((this.eventDateId == null) ? 0 : this.eventDateId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventDateVote (");

        sb.append(id);
        sb.append(", ").append(votingPerson);
        sb.append(", ").append(eventDateId);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
