/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Persons implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer personId;
    private String name;

    public Persons() {
    }

    public Persons(Persons value) {
        this.personId = value.personId;
        this.name = value.name;
    }

    public Persons(
            Integer personId,
            String name
    ) {
        this.personId = personId;
        this.name = name;
    }

    /**
     * Getter for <code>PERSONS.PERSON_ID</code>.
     */
    public Integer getPersonId() {
        return this.personId;
    }

    /**
     * Setter for <code>PERSONS.PERSON_ID</code>.
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * Getter for <code>PERSONS.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>PERSONS.NAME</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Persons other = (Persons) obj;
        if (personId == null) {
            if (other.personId != null)
                return false;
        } else if (!personId.equals(other.personId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.personId == null) ? 0 : this.personId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Persons (");

        sb.append(personId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
