/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProposedDates implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer proposedDateId;
    private LocalDate eventDate;
    private Long eventId;

    public ProposedDates() {
    }

    public ProposedDates(ProposedDates value) {
        this.proposedDateId = value.proposedDateId;
        this.eventDate = value.eventDate;
        this.eventId = value.eventId;
    }

    public ProposedDates(
            Integer proposedDateId,
            LocalDate eventDate,
            Long eventId
    ) {
        this.proposedDateId = proposedDateId;
        this.eventDate = eventDate;
        this.eventId = eventId;
    }

    /**
     * Getter for <code>PROPOSED_DATES.PROPOSED_DATE_ID</code>.
     */
    public Integer getProposedDateId() {
        return this.proposedDateId;
    }

    /**
     * Setter for <code>PROPOSED_DATES.PROPOSED_DATE_ID</code>.
     */
    public void setProposedDateId(Integer proposedDateId) {
        this.proposedDateId = proposedDateId;
    }

    /**
     * Getter for <code>PROPOSED_DATES.EVENT_DATE</code>.
     */
    public LocalDate getEventDate() {
        return this.eventDate;
    }

    /**
     * Setter for <code>PROPOSED_DATES.EVENT_DATE</code>.
     */
    public void setEventDate(LocalDate eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * Getter for <code>PROPOSED_DATES.EVENT_ID</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>PROPOSED_DATES.EVENT_ID</code>.
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProposedDates other = (ProposedDates) obj;
        if (proposedDateId == null) {
            if (other.proposedDateId != null)
                return false;
        } else if (!proposedDateId.equals(other.proposedDateId))
            return false;
        if (eventDate == null) {
            if (other.eventDate != null)
                return false;
        } else if (!eventDate.equals(other.eventDate))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        } else if (!eventId.equals(other.eventId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.proposedDateId == null) ? 0 : this.proposedDateId.hashCode());
        result = prime * result + ((this.eventDate == null) ? 0 : this.eventDate.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProposedDates (");

        sb.append(proposedDateId);
        sb.append(", ").append(eventDate);
        sb.append(", ").append(eventId);

        sb.append(")");
        return sb.toString();
    }
}
