/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Votes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Long votingPersonId;
    private Long proposedDates;

    public Votes() {
    }

    public Votes(Votes value) {
        this.id = value.id;
        this.votingPersonId = value.votingPersonId;
        this.proposedDates = value.proposedDates;
    }

    public Votes(
            Integer id,
            Long votingPersonId,
            Long proposedDates
    ) {
        this.id = id;
        this.votingPersonId = votingPersonId;
        this.proposedDates = proposedDates;
    }

    /**
     * Getter for <code>VOTES.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>VOTES.ID</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>VOTES.VOTING_PERSON_ID</code>.
     */
    public Long getVotingPersonId() {
        return this.votingPersonId;
    }

    /**
     * Setter for <code>VOTES.VOTING_PERSON_ID</code>.
     */
    public void setVotingPersonId(Long votingPersonId) {
        this.votingPersonId = votingPersonId;
    }

    /**
     * Getter for <code>VOTES.PROPOSED_DATES</code>.
     */
    public Long getProposedDates() {
        return this.proposedDates;
    }

    /**
     * Setter for <code>VOTES.PROPOSED_DATES</code>.
     */
    public void setProposedDates(Long proposedDates) {
        this.proposedDates = proposedDates;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Votes other = (Votes) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (votingPersonId == null) {
            if (other.votingPersonId != null)
                return false;
        } else if (!votingPersonId.equals(other.votingPersonId))
            return false;
        if (proposedDates == null) {
            if (other.proposedDates != null)
                return false;
        } else if (!proposedDates.equals(other.proposedDates))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.votingPersonId == null) ? 0 : this.votingPersonId.hashCode());
        result = prime * result + ((this.proposedDates == null) ? 0 : this.proposedDates.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Votes (");

        sb.append(id);
        sb.append(", ").append(votingPersonId);
        sb.append(", ").append(proposedDates);

        sb.append(")");
        return sb.toString();
    }
}
