/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq;


import fi.hopeton.jooq.tables.EventDate;
import fi.hopeton.jooq.tables.EventDateVote;
import fi.hopeton.jooq.tables.Events;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>EVENT_DATE</code>.
     */
    public final EventDate EVENT_DATE = EventDate.EVENT_DATE;

    /**
     * The table <code>EVENT_DATE_VOTE</code>.
     */
    public final EventDateVote EVENT_DATE_VOTE = EventDateVote.EVENT_DATE_VOTE;

    /**
     * The table <code>EVENTS</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                EventDate.EVENT_DATE,
                EventDateVote.EVENT_DATE_VOTE,
                Events.EVENTS);
    }
}
