/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq;


import fi.hopeton.jooq.tables.EventDate;
import fi.hopeton.jooq.tables.EventDateVote;
import fi.hopeton.jooq.tables.Events;
import fi.hopeton.jooq.tables.records.EventDateRecord;
import fi.hopeton.jooq.tables.records.EventDateVoteRecord;
import fi.hopeton.jooq.tables.records.EventsRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventDateRecord> CONSTRAINT_5 = Internal.createUniqueKey(EventDate.EVENT_DATE, DSL.name("CONSTRAINT_5"), new TableField[]{EventDate.EVENT_DATE.ID}, true);
    public static final UniqueKey<EventDateVoteRecord> CONSTRAINT_D = Internal.createUniqueKey(EventDateVote.EVENT_DATE_VOTE, DSL.name("CONSTRAINT_D"), new TableField[]{EventDateVote.EVENT_DATE_VOTE.ID}, true);
    public static final UniqueKey<EventsRecord> CONSTRAINT_7 = Internal.createUniqueKey(Events.EVENTS, DSL.name("CONSTRAINT_7"), new TableField[]{Events.EVENTS.ID}, true);
    public static final UniqueKey<EventsRecord> CONSTRAINT_7A = Internal.createUniqueKey(Events.EVENTS, DSL.name("CONSTRAINT_7A"), new TableField[]{Events.EVENTS.NAME}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EventDateRecord, EventsRecord> CONSTRAINT_59 = Internal.createForeignKey(EventDate.EVENT_DATE, DSL.name("CONSTRAINT_59"), new TableField[]{EventDate.EVENT_DATE.EVENT_ID}, Keys.CONSTRAINT_7, new TableField[]{Events.EVENTS.ID}, true);
    public static final ForeignKey<EventDateVoteRecord, EventDateRecord> CONSTRAINT_D5 = Internal.createForeignKey(EventDateVote.EVENT_DATE_VOTE, DSL.name("CONSTRAINT_D5"), new TableField[]{EventDateVote.EVENT_DATE_VOTE.EVENT_DATE_ID}, Keys.CONSTRAINT_5, new TableField[]{EventDate.EVENT_DATE.ID}, true);
}
