/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq;


import fi.hopeton.jooq.tables.EventDate;
import fi.hopeton.jooq.tables.EventDateVote;
import fi.hopeton.jooq.tables.Events;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>EVENT_DATE</code>.
     */
    public static final EventDate EVENT_DATE = EventDate.EVENT_DATE;

    /**
     * The table <code>EVENT_DATE_VOTE</code>.
     */
    public static final EventDateVote EVENT_DATE_VOTE = EventDateVote.EVENT_DATE_VOTE;

    /**
     * The table <code>EVENTS</code>.
     */
    public static final Events EVENTS = Events.EVENTS;
}
