/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq;


import fi.hopeton.jooq.tables.Events;
import fi.hopeton.jooq.tables.Persons;
import fi.hopeton.jooq.tables.ProposedDates;
import fi.hopeton.jooq.tables.Votes;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>EVENTS</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>PERSONS</code>.
     */
    public static final Persons PERSONS = Persons.PERSONS;

    /**
     * The table <code>PROPOSED_DATES</code>.
     */
    public static final ProposedDates PROPOSED_DATES = ProposedDates.PROPOSED_DATES;

    /**
     * The table <code>VOTES</code>.
     */
    public static final Votes VOTES = Votes.VOTES;
}
