/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.daos;


import fi.hopeton.jooq.tables.Events;
import fi.hopeton.jooq.tables.records.EventsRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventsDao extends DAOImpl<EventsRecord, fi.hopeton.jooq.tables.pojos.Events, Integer> {

    /**
     * Create a new EventsDao without any configuration
     */
    public EventsDao() {
        super(Events.EVENTS, fi.hopeton.jooq.tables.pojos.Events.class);
    }

    /**
     * Create a new EventsDao with an attached configuration
     */
    public EventsDao(Configuration configuration) {
        super(Events.EVENTS, fi.hopeton.jooq.tables.pojos.Events.class, configuration);
    }

    @Override
    public Integer getId(fi.hopeton.jooq.tables.pojos.Events object) {
        return object.getEventId();
    }

    /**
     * Fetch records that have <code>EVENT_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<fi.hopeton.jooq.tables.pojos.Events> fetchRangeOfEventId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Events.EVENTS.EVENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>EVENT_ID IN (values)</code>
     */
    public List<fi.hopeton.jooq.tables.pojos.Events> fetchByEventId(Integer... values) {
        return fetch(Events.EVENTS.EVENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>EVENT_ID = value</code>
     */
    public fi.hopeton.jooq.tables.pojos.Events fetchOneByEventId(Integer value) {
        return fetchOne(Events.EVENTS.EVENT_ID, value);
    }

    /**
     * Fetch records that have <code>NAME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<fi.hopeton.jooq.tables.pojos.Events> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Events.EVENTS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<fi.hopeton.jooq.tables.pojos.Events> fetchByName(String... values) {
        return fetch(Events.EVENTS.NAME, values);
    }
}
