/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.records;


import fi.hopeton.jooq.tables.EventDate;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventDateRecord extends UpdatableRecordImpl<EventDateRecord> implements Record3<Long, LocalDate, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached EventDateRecord
     */
    public EventDateRecord() {
        super(EventDate.EVENT_DATE);
    }

    /**
     * Create a detached, initialised EventDateRecord
     */
    public EventDateRecord(Long id, LocalDate proposedDate, Long eventId) {
        super(EventDate.EVENT_DATE);

        setId(id);
        setProposedDate(proposedDate);
        setEventId(eventId);
    }

    /**
     * Getter for <code>EVENT_DATE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>EVENT_DATE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>EVENT_DATE.PROPOSED_DATE</code>.
     */
    public LocalDate getProposedDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>EVENT_DATE.PROPOSED_DATE</code>.
     */
    public void setProposedDate(LocalDate value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>EVENT_DATE.EVENT_ID</code>.
     */
    public Long getEventId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>EVENT_DATE.EVENT_ID</code>.
     */
    public void setEventId(Long value) {
        set(2, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Long, LocalDate, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, LocalDate, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EventDate.EVENT_DATE.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return EventDate.EVENT_DATE.PROPOSED_DATE;
    }

    @Override
    public Field<Long> field3() {
        return EventDate.EVENT_DATE.EVENT_ID;
    }

    @Override
    public Long component3() {
        return getEventId();
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getProposedDate();
    }

    @Override
    public Long value3() {
        return getEventId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getProposedDate();
    }

    @Override
    public EventDateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventDateRecord value2(LocalDate value) {
        setProposedDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public EventDateRecord value3(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventDateRecord values(Long value1, LocalDate value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
