/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.records;


import fi.hopeton.jooq.tables.Events;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Integer eventId, String name) {
        super(Events.EVENTS);

        setEventId(eventId);
        setName(name);
    }

    /**
     * Getter for <code>EVENTS.EVENT_ID</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>EVENTS.EVENT_ID</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>EVENTS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>EVENTS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Events.EVENTS.EVENT_ID;
    }

    @Override
    public Field<String> field2() {
        return Events.EVENTS.NAME;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public EventsRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public EventsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public EventsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
