/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.records;


import fi.hopeton.jooq.tables.Events;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Long id, String name) {
        super(Events.EVENTS);

        setId(id);
        setName(name);
    }

    /**
     * Getter for <code>EVENTS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Getter for <code>EVENTS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>EVENTS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>EVENTS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Field<String> field2() {
        return Events.EVENTS.NAME;
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Field<Long> field1() {
        return Events.EVENTS.ID;
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public EventsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public Long value1() {
        return getId();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public EventsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventsRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
