/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.records;


import fi.hopeton.jooq.tables.EventDateVote;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventDateVoteRecord extends UpdatableRecordImpl<EventDateVoteRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached EventDateVoteRecord
     */
    public EventDateVoteRecord() {
        super(EventDateVote.EVENT_DATE_VOTE);
    }

    /**
     * Create a detached, initialised EventDateVoteRecord
     */
    public EventDateVoteRecord(Long id, String votingPerson, Long eventDateId) {
        super(EventDateVote.EVENT_DATE_VOTE);

        setId(id);
        setVotingPerson(votingPerson);
        setEventDateId(eventDateId);
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>EVENT_DATE_VOTE.VOTING_PERSON</code>.
     */
    public String getVotingPerson() {
        return (String) get(1);
    }

    /**
     * Setter for <code>EVENT_DATE_VOTE.VOTING_PERSON</code>.
     */
    public void setVotingPerson(String value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>EVENT_DATE_VOTE.EVENT_DATE_ID</code>.
     */
    public Long getEventDateId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>EVENT_DATE_VOTE.EVENT_DATE_ID</code>.
     */
    public void setEventDateId(Long value) {
        set(2, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EventDateVote.EVENT_DATE_VOTE.ID;
    }

    @Override
    public Field<String> field2() {
        return EventDateVote.EVENT_DATE_VOTE.VOTING_PERSON;
    }

    @Override
    public Field<Long> field3() {
        return EventDateVote.EVENT_DATE_VOTE.EVENT_DATE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getVotingPerson();
    }

    @Override
    public Long component3() {
        return getEventDateId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getVotingPerson();
    }

    @Override
    public Long value3() {
        return getEventDateId();
    }

    @Override
    public EventDateVoteRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventDateVoteRecord value2(String value) {
        setVotingPerson(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public EventDateVoteRecord value3(Long value) {
        setEventDateId(value);
        return this;
    }

    @Override
    public EventDateVoteRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
