/*
 * This file is generated by jOOQ.
 */
package fi.hopeton.jooq.tables.records;


import fi.hopeton.jooq.tables.ProposedDates;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProposedDatesRecord extends UpdatableRecordImpl<ProposedDatesRecord> implements Record3<Integer, LocalDate, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached ProposedDatesRecord
     */
    public ProposedDatesRecord() {
        super(ProposedDates.PROPOSED_DATES);
    }

    /**
     * Getter for <code>PROPOSED_DATES.PROPOSED_DATE_ID</code>.
     */
    public Integer getProposedDateId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised ProposedDatesRecord
     */
    public ProposedDatesRecord(Integer proposedDateId, LocalDate eventDate, Long eventId) {
        super(ProposedDates.PROPOSED_DATES);

        setProposedDateId(proposedDateId);
        setEventDate(eventDate);
        setEventId(eventId);
    }

    /**
     * Getter for <code>PROPOSED_DATES.EVENT_DATE</code>.
     */
    public LocalDate getEventDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>PROPOSED_DATES.PROPOSED_DATE_ID</code>.
     */
    public void setProposedDateId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PROPOSED_DATES.EVENT_ID</code>.
     */
    public Long getEventId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDate, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, LocalDate, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProposedDates.PROPOSED_DATES.PROPOSED_DATE_ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return ProposedDates.PROPOSED_DATES.EVENT_DATE;
    }

    @Override
    public Field<Long> field3() {
        return ProposedDates.PROPOSED_DATES.EVENT_ID;
    }

    @Override
    public Integer component1() {
        return getProposedDateId();
    }

    @Override
    public LocalDate component2() {
        return getEventDate();
    }

    @Override
    public Long component3() {
        return getEventId();
    }

    @Override
    public Integer value1() {
        return getProposedDateId();
    }

    @Override
    public LocalDate value2() {
        return getEventDate();
    }

    @Override
    public Long value3() {
        return getEventId();
    }

    @Override
    public ProposedDatesRecord value1(Integer value) {
        setProposedDateId(value);
        return this;
    }

    @Override
    public ProposedDatesRecord value2(LocalDate value) {
        setEventDate(value);
        return this;
    }

    @Override
    public ProposedDatesRecord value3(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public ProposedDatesRecord values(Integer value1, LocalDate value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>PROPOSED_DATES.EVENT_DATE</code>.
     */
    public void setEventDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Setter for <code>PROPOSED_DATES.EVENT_ID</code>.
     */
    public void setEventId(Long value) {
        set(2, value);
    }
}
